### ISSUE TITLE
Error while node is syncing

### ISSUE THREAD

**Issue by diego-G** [karek314/lisk-network-reporter#6]
The application stops reporting and throws an error while node is syncing. It restarts after a while hitting the same point again and again.

Logs:
```
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] ==> Got same block: 5878502
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Validate
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Block Data:  { number: 5878502,
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:   hash: '11298833324342216287',
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:   difficulty: '11298833324342216287',
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:   totalDifficulty: '11298833324342216287',
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:   transactions: [],
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:   uncles: '400000000' }
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Block: 5878502/5878502
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Transactions included in Block: 0
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] ==> Got same block: 5878502
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] ==> Got 0 pending txs in 1257 ms
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Last pending / current pending 0/0
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Delegate Count: 123
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= SYNC STARTED: true
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =✘= ReferenceError: syncing_blocks is not defined
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at IncomingMessage.<anonymous> (/home/admin/git/lisk-network-reporter/lib/node.js:201:27)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at emitNone (events.js:91:20)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at IncomingMessage.emit (events.js:185:7)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at endReadableNT (_stream_readable.js:934:12)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at args.(anonymous function) (/home/admin/.nvm/versions/node/v6.14.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00:     at process._tickCallback (internal/process/next_tick.js:98:9)
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK]     
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK]     NET STATS CLIENT
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK]     v1.0.0
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK]     
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK]     
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =i= Starting connection to Lisk Node
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =✘= Connection attempt #0 failed
5|lisk-network-reporter  | 2018-11-08 14:09 +00:00: [LISK] =✘= Trying again in 500 ms
```

I am using Node `6.14.3` and Lisk `v1.4.0` from development branch.

![screenshot 2018-11-08 at 15 10 52](https://user-images.githubusercontent.com/1387244/48203805-b6561980-e368-11e8-869e-839c079ef27c.png)

**Comment by karek314** [comment]
Thanks for reporting this. It should be fixed with https://github.com/karek314/lisk-network-reporter/commit/ae399ddeb491b3832cef20cd9ea2d6fc92063b3c
